const mediaLibary={
    about:{
        img:require('../media/about/005035280005.jpg'),
    },
    creative:{
        domalii:{
            name:'dom alii',
            displayImage:require('../media/creative/domAlii/TIG_6554.jpg'),
            photos:[
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6521.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6538.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6545-2.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6545-3.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6545.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6554.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6555.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6576.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6615-3.jpg'),
            description:'',
            },
            {
            name:'',
            url:require('../media/creative/domAlii/TIG_6618.jpg'),
            description:'',
            },
        ]},
        lightheadtops:{
            name:'lighthead tops',
            displayImage:require('../media/creative/lightHeadTops/000076660024.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/creative/lightHeadTops/000076660013.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/lightHeadTops/000076660024.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/lightHeadTops/000076660025.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/lightHeadTops/Tiger1.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/lightHeadTops/tiger2.jpg'),
                description:'',
            },
        ]},
        omarijabari:{
            name:'omari jabari',
            displayImage:require('../media/creative/omariJabari/TIG_1096.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_0992.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_0995.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_0998.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1006.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1010.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1029.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1039.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1057.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1083.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/omariJabari/TIG_1096.jpg'),
                description:'',
            },
        ]},
        ryanmask:{
            name:'ryan mask',
            displayImage:require('../media/creative/ryanMask/000094860002.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860001.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860002.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860003.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860006.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860010.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860011.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860013.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/creative/ryanMask/000094860015.jpg'),
                description:'',
            },
        ]},
    },
    editorial:{
        fasinfrank:{   
            name:'f as in frank',
            displayImage:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500017.jpg'),
            photos:[
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0926.jpg'),
                    description:'',
                    location:'fasinfrank',
                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0942.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0950.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0972.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0984.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_0995.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_1006.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_1035.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_1047.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Danny',
                    url:require('../media/editorial/fAsInFrank/danny/TIG_1055.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3226.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3232.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3235.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3252.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3258.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3260.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Liam and Vince',
                    url:require('../media/editorial/fAsInFrank/liamVince/TIG_3274.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99490006.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99490015.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99490021.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500011.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500012.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500017.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500020.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500021.jpg'),
                    description:'',
                    location:'fasinfrank',

                },
                {
                    name:'F as in Frank - Saint, Paula, and Stephanie',
                    url:require('../media/editorial/fAsInFrank/saintPaulaStephanie/99500022.jpg'),
                    description:'',
                    location:'fasinfrank',
                },
        ]},
        getfreshcompany:{
            name:'get fresh company',
            displayImage:require('../media/editorial/getFreshCompany/EDITED/TIG_5056.jpg'),
            photos:[
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5039.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5056.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5066.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5097.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5127.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5145.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5223.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5257.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5299.jpg'),
                description:'',
                location:'getfreshcompany',
            },
            {
                name:'Get Fresh Company',
                url:require('../media/editorial/getFreshCompany/EDITED/TIG_5316.jpg'),
                description:'',
                location:'getfreshcompany',
            },
        ]},
        layeredidentity:{
            name:'layered identity',
            displayImage:require('../media/editorial/layeredIdentity/EDITED/TIG_3569.jpg'),
            photos:[
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3471.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3481.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3500.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3507.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3519.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3524.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3530.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3555.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3563-2.jpg'),
                description:'',
                location:'layeredidentity',
            },
            {
                name:'Layered Identity',
                url:require('../media/editorial/layeredIdentity/EDITED/TIG_3569.jpg'),
                description:'',
                location:'layeredidentity',
            },
        ]},
        mindofagenius:{
            name:'mind of a genius',
            displayImage:require('../media/editorial/mindOfAGenius/TIG_2148.jpg'),
            photos:[
            {
                name:'Mind of a Genius',
                url:require('../media/editorial/mindOfAGenius/TIG_2079.jpg'),
                description:'',
                location:'mindofagenius',
            },
            {
                name:'Mind of a Genius',
                url:require('../media/editorial/mindOfAGenius/TIG_2091.jpg'),
                description:'',
                location:'mindofagenius',
            },
            {
                name:'Mind of a Genius',
                url:require('../media/editorial/mindOfAGenius/TIG_2146.jpg'),
                description:'',
                location:'mindofagenius',
            },
            {
                name:'Mind of a Genius',
                url:require('../media/editorial/mindOfAGenius/TIG_2148.jpg'),
                description:'',
                location:'mindofagenius',
            },
            {
                name:'Mind of a Genius',
                url:require('../media/editorial/mindOfAGenius/TIG_2153.jpg'),
                description:'',
                location:'mindofagenius',
            },
        ]},
        severenature:{
            name:'severe nature',
            displayImage:require('../media/editorial/severeNature/TIG_7999.jpg'),
            photos:[
            {
                name:'Severe Nature',
                url:require('../media/editorial/severeNature/TIG_7924.jpg'),
                description:'',
                location:'severenature',
            },
            {
                name:'Severe Nature',
                url:require('../media/editorial/severeNature/TIG_7932.jpg'),
                description:'',
                location:'severenature',
            },
            {
                name:'Severe Nature',
                url:require('../media/editorial/severeNature/TIG_7955.jpg'),
                description:'',
                location:'severenature',
            },
            {
                name:'Severe Nature',
                url:require('../media/editorial/severeNature/TIG_7967.jpg'),
                description:'',
                location:'severenature',
            },
            {
                name:'Severe Nature',
                url:require('../media/editorial/severeNature/TIG_7999.jpg'),
                description:'',
                location:'severenature',
            },
        ]},
        suspend:{
            name:'suspend',
            displayImage:require('../media/editorial/suspend/TIG_6676.jpg'),
            photos:[
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6508.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6520.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6575.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6586.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6614.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6645.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6661.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6668.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6676.jpg'),
                description:'',
                location:'suspend',
            },
            {
                name:'Suspend',
                url:require('../media/editorial/suspend/TIG_6680.jpg'),
                description:'',
                location:'suspend',
            },
        ]},
        vintageoutlaw:{
            name:'vintage outlaw',
            displayImage:require('../media/editorial/vintageOutlaw/000057470002.jpg'),
            photos:[
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057470002.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057470019.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480004.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480006.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480011.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480016.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480017.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480018.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480022.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
            {
                name:'Vintage Outlaw',
                url:require('../media/editorial/vintageOutlaw/000057480023.jpg'),
                description:'',
                location:'vintageoutlaw',
            },
        ]}
    },
    logo:[
        require('../media/logo/TS_LOGO_FINAL_BV1.png'),
        require('../media/logo/TS_LOGO_FINAL_BV2.png'),
        require('../media/logo/TS_LOGO_FINAL_WV1.png'),
        require('../media/logo/TS_LOGO_FINAL_WV2.png'),
    ],
    music:{
        eljay:{
            name:'eljay',
            displayImage:require('../media/music/eljay/popstar/TIG_8876.jpg'),
            photos:[
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8801.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8805.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8815.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8829.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8850.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8863.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/popstar/TIG_8876.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/Eljay-Cover-3-with-text.instagram.gif'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6019.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6034.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6058.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6126.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6129.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6158.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6173.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6195.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6244.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/eljay/redBlue/TIG_6296.jpg'),
                    description:'',
                },
            
        ]},
        jalensantoy:{
            name:'jalen santoy',
            displayImage:require('../media/music/jalenSantoy/TIG_7489.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7461.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7471.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7476.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7487.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7489.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7494.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/jalenSantoy/TIG_7506.jpg'),
                description:'',
            },
        ]},
        neenyo:{
            name:'neenyo',
            displayImage:require('../media/music/neenyo/000060620018.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/neenyo/000060620003.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620008.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620010.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620016.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620018.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620019.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620021.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/neenyo/000060620024.jpg'),
                description:'',
            },
        ]},
        nivaavideoseries:{
            name:'nivaa video series',
            displayImage:require('../media/music/nivaaVideoSeries/TIG_8796.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8608.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8615.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8653.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8685.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8690.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8694.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8715.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8796.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8823.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/nivaaVideoSeries/TIG_8841.jpg'),
                description:'',
            },
        ]},
        pvrx:{
            name:'pvrx',
            displayImage:require('../media/music/PVRX/niagaraFalls/TIG_1405.jpg'),
            photos:[
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1110.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1181.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1203.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1227.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1320.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1358.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1379.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1405.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1434.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/niagaraFalls/TIG_1646.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/000097530008.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/000097530011.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/000097530018.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_2911.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_2936.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_2963.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_2974.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_3033.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_3047.jpg'),
                    description:'',
                },
                {
                    name:'',
                    url:require('../media/music/PVRX/nunNewBTS/TIG_3133.jpg'),
                    description:'',
                },
        ]},
        shockwes:{
            name:'shock wes',
            displayImage:require('../media/music/sheckWes/73920021.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/sheckWes/73920018.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/sheckWes/73920021.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/sheckWes/73920023.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/sheckWes/73920024.jpg'),
                description:'',
            },
        ]},
        twelveam:{
            name:'12 am',
            displayImage:require('../media/music/twelveAM/TIG_7274.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7269.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7274.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7284-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7296.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7316.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7319.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7327.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7369.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7379.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/twelveAM/TIG_7383.jpg'),
                description:'',
            },
        ]},
        uncrwnd_vl9:{
            name:'uncrwnd_v19',
            displayImage:require('../media/music/UNCRWND_VL.9/TIG_6095.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_5809-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_5850.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_5875-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_5990.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_6095.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_6125.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_6137.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_6190.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/UNCRWND_VL.9/TIG_6247.jpg'),
                description:'',
            },
        ]},
        zhu:{
            name:'zhu',
            displayImage:require('../media/music/zhu/TIG_2190-2.jpg'),
            photos:[
            {
                name:'',
                url:require('../media/music/zhu/TIG_2190-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/zhu/TIG_2239-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/zhu/TIG_2242-2.jpg'),
                description:'',
            },
            {
                name:'',
                url:require('../media/music/zhu/TIG_2243-2.jpg'),
                description:'',
            },
        ]},
    },
    videos:[
        {
            name:'Jessie Reyez - Columbia Doc',
            url:require('../media/videos/Jessie_Reyez_-_Colombia_Doc.mp4'),
            thumbnail:require('../media/videos/j-reyez-thumbnail.JPG'),
            description:'',
        },
        {
            name:'Grammy Short Doc 2',
            url:require('../media/videos/Jessie_Reyez_-_Grammy_Short_Doc_2.mp4'),
            thumbnail:require('../media/videos/j-reyez-grammy-thumbnail.JPG'),
            description:'',
        },
        {
            name:'NIIVA - Love Games',
            url:require('../media/videos/NIIVA_-_Love_Games.mp4'),
            thumbnail:require('../media/videos/niiva-thumbnail.JPG'),
            description:'',
        },
        {
            name:'Uptown Boyban - Read My Mind',
            url:require('../media/videos/Uptown_Boyband_-_Read_My_Mind.mp4'),
            thumbnail:require('../media/videos/uptown-thumbnail.JPG'),
            description:'',
        },
    ],
}

export default mediaLibary